apiVersion: v1
kind: Namespace
metadata:
  name: prod-fintech
  labels:
    istio-injection: enabled
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-all
  namespace: prod-fintech
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress
